ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_notified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS conversation_id VARCHAR(160);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fulfilment VARCHAR(32);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(160);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_payment_reference ON orders(payment_reference) WHERE payment_reference IS NOT NULL;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS line_total_kobo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS metadata_json TEXT;
